### ISSUE TITLE
Random panic

### ISSUE THREAD

**Issue by themester** [robfig/cron#145]
This is the stacktrace:
```
2018/05/28 13:19:22 cron: panic running job: runtime error: invalid memory address or nil pointer dereference
goroutine 4816 [running]:
github.com/robfig/cron.(*Cron).runWithRecovery.func1(0xc00042b680)
  /home/mester/.go/src/github.com/robfig/cron/cron.go:161 +0xbc
panic(0x8612e0, 0xd09f60)
  /home/mester/Go/src/runtime/panic.go:494 +0x1b9
main.state(0xc0002d2400, 0xc00041d8e0)
  /home/mester/.../bot.go:91 +0x29cf
main.main.func1()
  /home/mester/.../main.go:51 +0x33
github.com/robfig/cron.FuncJob.Run(0xc00041d900)
  /home/mester/.go/src/github.com/robfig/cron/cron.go:92 +0x25
github.com/robfig/cron.(*Cron).runWithRecovery(0xc00042b680, 0x930500, 0xc00041d900)
  /home/mester/.go/src/github.com/robfig/cron/cron.go:165 +0x57
created by github.com/robfig/cron.(*Cron).run
  /home/mester/.go/src/github.com/robfig/cron/cron.go:199 +0x6b3
```

**Comment by robfig** [comment]
The frame immediately before panic.go is in your code:

  /home/mester/.../bot.go:91 +0x29cf

Look there for the nil pointer dereference

**Comment by chen-lee-li** [comment]
Have you solved this problem？
