### ISSUE TITLE
Possible deadlock

### ISSUE THREAD

**Issue by kless** [robfig/cron#48]
It looks that there is a  a deadlock somewhere.
I've used tried of using cron with a service manager, and the error is:

```
Mar 11 18:51:54 serve foo[2257]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 11 18:51:54 serve foo[2257]: [signal 0xb code=0x1 addr=0x30 pc=0x4acd83]
Mar 11 18:51:54 serve foo[2257]: goroutine 1 [running]:
Mar 11 18:51:54 serve foo[2257]: panic(0x6bc260, 0xc82000a0b0)
Mar 11 18:51:54 serve foo[2257]:         /usr/local/lib/go/src/runtime/panic.go:464 +0x3ff
Mar 11 18:51:54 serve foo[2257]: github.com/robfig/cron.(*Cron).AddJob(0x0, 0x70b480, 0xa, 0x7f227577e528, 0x775390, 0x0, 0x0)
Mar 11 18:51:54 serve foo[2257]:         /usr/local/lib/go-3party/src/github.com/robfig/cron/cron.go:96 +0x1c3
Mar 11 18:51:54 serve foo[2257]: github.com/robfig/cron.(*Cron).AddFunc(0x0, 0x70b480, 0xa, 0x775390, 0x0, 0x0)
Mar 11 18:51:54 serve foo[2257]:         /usr/local/lib/go-3party/src/github.com/robfig/cron/cron.go:87 +0x8d
Mar 11 18:51:54 serve foo[2257]: main.Program.Start(0x7f227577e4c0, 0xc820062140, 0x0, 0xc82005a600, 0xc820056180, 0x7f227577e4c0, 0xc820062140, 0x0, 0x0)
Mar 11 18:51:54 serve foo[2257]:         /data/taka/code/go/src/indoo/cmd/foo/foo.go:68 +0xb5
Mar 11 18:51:54 serve foo[2257]: main.(*Program).Start(0xc82005c6c0, 0x7f227577e4c0, 0xc820062140, 0x0, 0x0)
Mar 11 18:51:54 serve foo[2257]:         <autogenerated>:1 +0xe0
Mar 11 18:51:54 serve foo[2257]: github.com/kardianos/service.(*systemd).Run(0xc820062140, 0x0, 0x0)
Mar 11 18:51:54 serve foo[2257]:         /usr/local/lib/go-3party/src/github.com/kardianos/service/service_systemd_linux.go:126 +0xc4
Mar 11 18:51:54 serve foo[2257]: main.main()
Mar 11 18:51:54 serve foo[2257]:         /data/taka/code/go/src/indoo/cmd/foo/foo.go:50 +0x55c

```

And the code is:
```
package main

import (
	"flag"
	"os"
	"time"

	log "github.com/Sirupsen/logrus"
	"github.com/kardianos/service"
	"github.com/robfig/cron"
)

var (
	FlagInstall   = flag.Bool("install", false, "install setups up the service in the OS")
	FlagUninstall = flag.Bool("uninstall", false, "uninstall removes the service from the OS")
)

func main() {
	flag.Parse()

	serviceConfig := &service.Config{
		Name:        "foo",
		DisplayName: "Foo daemon",
		Description: "tester of daemon",
		//UserName:    "ubuntu",
	}

	serv, err := service.New(Program{}, serviceConfig)
	if err != nil {
		log.Fatal(err)
	}
	serviceManager := service.ChosenSystem()

	if *FlagInstall {
		if !serviceManager.Detect() {
			log.Fatal("the service manager of this system is not available")
		}
		if err = serv.Install(); err != nil {
			log.Fatal(err)
		}
		os.Exit(0)
	} else if *FlagUninstall {
		if err = serv.Uninstall(); err != nil {
			log.Fatal(err)
		}
		os.Exit(0)
	}

	if err = serv.Run(); err != nil {
		log.Fatal(err)
	}
}

type Program struct {
	service service.Service
	cron_   *cron.Cron
}

func (p Program) Start(s service.Service) error {
	p.service = s
	p.cron_.AddFunc("@every 20s", func() {
		log.Print("++")
	})

	p.cron_.Start()
	go p.run()
	log.Info("Start")
	return nil
}

func (p Program) run() {
	//p.cron_.Start()

	log.Info("run")
}

func (p Program) Stop(s service.Service) error {
	p.cron_.Stop()
	log.Info("Stop")

	time.Sleep(10*time.Millisecond)
	return nil
}
```

**Comment by kless** [comment]
There is to use a pointer ```func (p *Program)```
